app.index:
    path: /
    controller: App\AirQuality\Infrastructure\Controller\GetAirQualityIndexController
    methods: [GET]

app.search:
    path: /search
    controller: App\AirQuality\Infrastructure\Controller\GetCityAirQualityController
    methods: [POST]
