app.index:
    path: /
    controller: App\AirQuality\Infrastructure\Controller\GetAirQualityIndexController
    method: GET

app.search:
    path: /search
    controller: App\AirQuality\Infrastructure\Controller\GetCityAirQualityController
    method: POST
